// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { MaxPlayerId, MaxPlayerIdTableId } from "./tables/MaxPlayerId.sol";
import { Players, PlayersData, PlayersTableId } from "./tables/Players.sol";
import { CalculatedCount, CalculatedCountTableId } from "./tables/CalculatedCount.sol";
